services:
  musicbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicbot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
